#!/usr/bin/env python3
"""BatteryMat Option B: select prospective DFT candidates + low-ranked controls.

Selects top-K never-DFT-evaluated candidates from the ranked cathode list and
K_ctrl low-ranked controls from the cathode-window pool, then writes:
  - out/prospective_selection.csv    (the chosen set, with ranks and scores)
  - out/launch_prospective.sh        (dft_prep.py init commands to run on the cluster)

Run:  python3 03_select_prospective.py --top 8 --controls 4
"""

import argparse
import csv
import os
import re

REPO = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
)
RANKED_CSV = os.path.join(REPO, "screening_cathode/cathode_candidates_ranked.csv")
LI_MIN_CSV = os.path.join(REPO, "average_voltage/Li_min.csv")
DFT_DONE_DIR = os.path.join(REPO, "screening_cathode/dft_inputs")
OUT_DIR = os.path.dirname(os.path.abspath(__file__))
V_MAX, V_MIN = 5.5, 1.0


def already_done():
    done = set()
    if os.path.isdir(DFT_DONE_DIR):
        for d in os.listdir(DFT_DONE_DIR):
            m = re.search(r"(JVASP-\d+)", d)
            if m:
                done.add(m.group(1))
    return done


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--top", type=int, default=8)
    ap.add_argument("--controls", type=int, default=4)
    args = ap.parse_args()
    os.makedirs(OUT_DIR, exist_ok=True)
    done = already_done()
    print(f"already DFT-evaluated (excluded): {sorted(done)}")

    # top-ranked: from the composite-score ranked shortlist
    top = []
    with open(RANKED_CSV) as f:
        for r in csv.DictReader(f):
            jid = r.get("jid", "")
            if jid and jid not in done:
                top.append({"jid": jid, "formula": r.get("formula", ""),
                            "score": float(r.get("score", "nan")),
                            "avg_v": float(r.get("avg_voltage", "nan")),
                            "ehull": r.get("ehull", ""), "group": "top"})
    top.sort(key=lambda x: -x["score"])
    top = top[: args.top]

    # controls: low end of the cathode-window pool (valid structures, poor rank)
    pool = []
    with open(LI_MIN_CSV) as f:
        for r in csv.DictReader(f):
            m = re.search(r"(JVASP-\d+)", r.get("name", ""))
            if not m:
                continue
            try:
                avg_v = float(r["avg_voltage"]); max_v = float(r["max_voltage"])
                profile = [float(x) for x in r["voltage_profile"].split(";") if x]
                min_v = min(profile) if profile else avg_v
            except (KeyError, ValueError):
                continue
            if max_v <= V_MAX and min_v > V_MIN:
                pool.append({"jid": m.group(1), "formula": "", "score": float("nan"),
                             "avg_v": avg_v, "ehull": "", "group": "control"})
    chosen_jids = {t["jid"] for t in top}
    controls = [p for p in sorted(pool, key=lambda x: x["avg_v"])
                if p["jid"] not in done and p["jid"] not in chosen_jids][: args.controls]

    sel = top + controls
    csv_path = os.path.join(OUT_DIR, "prospective_selection.csv")
    with open(csv_path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["group", "jid", "formula", "score", "avg_v", "ehull"])
        w.writeheader()
        for s in sel:
            w.writerow({k: s.get(k, "") for k in w.fieldnames})

    sh_path = os.path.join(OUT_DIR, "launch_prospective.sh")
    with open(sh_path, "w") as f:
        f.write("#!/bin/bash\n# Option B prospective DFT launch (run from screening_cathode/ on the cluster)\n")
        f.write("# Generated by 03_select_prospective.py - review before submitting.\nset -e\n\n")
        for s in sel:
            f.write(f"python dft_prep.py init {s['jid']}    # {s['group']}: "
                    f"avg_v={s['avg_v']:.2f} score={s['score']}\n")
    os.chmod(sh_path, 0o755)

    print(f"\nselected {len(top)} top candidates + {len(controls)} controls")
    for s in sel:
        print(f"  [{s['group']:7s}] {s['jid']:14s} avg_v={s['avg_v']:.2f} score={s['score']}")
    print(f"\nwrote {csv_path}\nwrote {sh_path}")
    print("\nNext: copy launch_prospective.sh to the cluster, add POTCARs, submit the arrays.")


if __name__ == "__main__":
    main()
