#!/usr/bin/env python3
"""Build the prospective-validation results table from harvested energies.json files.

Replicates dft_prep.py's voltage formula: V_step = (E_lo - E_hi)/dn + e_li_metal.
Average voltage = capacity-weighted mean over recorded steps
               = (E_last - E_first)/n_removed + e_li_metal.

Run:  python3 04_prospective_table.py
Output: out/prospective_table.md
"""

import csv
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DFT_INPUTS = os.path.normpath(os.path.join(HERE, "..", "dft_inputs"))

LABELS = {
    "JVASP-117419": ("LiCr2P2O8", "top"),
    "JVASP-141543": ("Rb2LiFeF6 (polymorph A)", "top"),
    "JVASP-117295": ("Li3FeO3", "top"),
    "JVASP-116849": ("LiV2F7", "top"),
    "JVASP-154749": ("Rb2LiFeF6 (polymorph B)", "top"),
    "JVASP-96563": ("Li2MgMn3O8", "top"),
    "JVASP-95533": ("LiCoH24C8N8O12", "top"),
    "JVASP-97428": ("LiH4SNO4", "top"),
    "JVASP-80802": ("LiY2Ga", "control"),
    "JVASP-77457": ("LiCa2Ag", "control"),
    "JVASP-85076": ("LiCaTl2", "control"),
    "JVASP-81829": ("LiMnIr2", "control"),
}

# tier-2 (ALIGNN-FF) predicted average voltages from the selection
tier2 = {}
with open(os.path.join(HERE, "prospective_selection.csv")) as f:
    for r in csv.DictReader(f):
        tier2[r["jid"]] = float(r["avg_v"])

rows = []
for ej in sorted(glob.glob(os.path.join(DFT_INPUTS, "*/supercell_*/energies.json"))):
    d = json.load(open(ej))
    jid = d["jid"]
    if jid not in LABELS:
        continue  # dft_inputs also holds the five commercial benchmark cathodes
    rec = sorted([s for s in d["steps"] if s.get("energy") is not None],
                 key=lambda s: s["n_li"], reverse=True)
    if len(rec) < 2:
        continue
    n_removed = rec[0]["n_li"] - rec[-1]["n_li"]
    avg_v = (rec[-1]["energy"] - rec[0]["energy"]) / n_removed + d["e_li_metal"]
    complete = rec[-1]["n_li"] == 0
    name, grp = LABELS[jid]
    pred = tier2[jid]
    rows.append({
        "jid": jid, "name": name, "grp": grp, "pred": pred, "dft": avg_v,
        "err": avg_v - pred, "func": d["functional"],
        "steps": f"{n_removed}/{d['n_li_total']}",
        "status": "complete" if complete else "partial",
    })

rows.sort(key=lambda r: (r["grp"] != "top", -r["pred"]))

lines = ["# Prospective DFT validation results (generated by 04_prospective_table.py)", ""]
lines.append("| Material | Group | Tier-2 pred (V) | DFT avg (V) | Error (V) | Functional | Li removed | Status |")
lines.append("|---|---|---|---|---|---|---|---|")
for r in rows:
    lines.append(f"| {r['name']} | {r['grp']} | {r['pred']:.2f} | {r['dft']:.2f} | "
                 f"{r['err']:+.2f} | {r['func']} | {r['steps']} | {r['status']} |")
lines.append("")

tops = [r for r in rows if r["grp"] == "top"]
ctrls = [r for r in rows if r["grp"] == "control"]
min_top = min(r["dft"] for r in tops)
max_ctrl = max(r["dft"] for r in ctrls)
mae = sum(abs(r["err"]) for r in rows) / len(rows)
lines.append(f"Top candidates: N={len(tops)}, DFT avg voltage range "
             f"{min_top:.2f} to {max(r['dft'] for r in tops):.2f} V.")
lines.append(f"Controls: N={len(ctrls)}, DFT range "
             f"{min(r['dft'] for r in ctrls):.2f} to {max_ctrl:.2f} V.")
lines.append(f"Separation: lowest top candidate ({min_top:.2f} V) vs highest control "
             f"({max_ctrl:.2f} V) -> {'NO OVERLAP' if min_top > max_ctrl else 'OVERLAP'}.")
lines.append(f"Tier-2 vs DFT MAE over all {len(rows)} materials: {mae:.2f} V.")
pA = next((r["dft"] for r in rows if r["jid"] == "JVASP-141543"), None)
pB = next((r["dft"] for r in rows if r["jid"] == "JVASP-154749"), None)
if pA and pB:
    lines.append(f"Rb2LiFeF6 polymorph agreement: {pA:.3f} vs {pB:.3f} V "
                 f"(delta {abs(pA-pB)*1000:.0f} mV).")

out = os.path.join(HERE, "prospective_table.md")
open(out, "w").write("\n".join(lines) + "\n")
print("\n".join(lines))
print(f"\nwrote {out}")
