#!/bin/bash
# Option B prospective DFT launch (run from screening_cathode/ on the cluster)
# Generated by 03_select_prospective.py - review before submitting.
set -e

python dft_prep.py init JVASP-117419    # top: avg_v=4.42 score=0.3256866255429928
python dft_prep.py init JVASP-141543    # top: avg_v=4.08 score=0.3156958611530508
python dft_prep.py init JVASP-117295    # top: avg_v=4.39 score=0.31056162542596205
python dft_prep.py init JVASP-116849    # top: avg_v=4.19 score=0.2965592761155006
python dft_prep.py init JVASP-154749    # top: avg_v=4.25 score=0.2851047183606379
python dft_prep.py init JVASP-96563    # top: avg_v=4.23 score=0.27638369237998855
python dft_prep.py init JVASP-95533    # top: avg_v=4.10 score=0.2748182933872677
python dft_prep.py init JVASP-97428    # top: avg_v=4.01 score=0.26037414899367517
python dft_prep.py init JVASP-80802    # control: avg_v=1.04 score=nan
python dft_prep.py init JVASP-77457    # control: avg_v=1.06 score=nan
python dft_prep.py init JVASP-85076    # control: avg_v=1.11 score=nan
python dft_prep.py init JVASP-81829    # control: avg_v=1.12 score=nan
